#ifndef GEHERRORDEFINE_H_
#define GEHERRORDEFINE_H_

#define GEH_ERROR_NONE 0
#define GEH_ERROR_NOT_ENOUGH_QUEUE 1
#define GEH_ERROR_NOT_ENOUGH_MEMORY 2
#define GEH_ERROR_DISCONNECTED 3

#endif // GEHERRORDEFINE_H_
